# Generated by Django 4.2 on 2023-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('données', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='libelle',
            field=models.TextField(max_length=200),
        ),
    ]
